config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'users#index'
  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end
 
  resources :users do
    resources :posts do
      member do
        post 'like'
        delete 'unlike'
      end
      resources :comments
      resources :likes
    end
  end  
  resources :likes, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  # Attributes: id, user_id, post_id, text, updated_at, created_at

  # Callbacks
  after_create :update_post_comments_counter
  after_destroy :update_post_comments_counter

  def update_post_comments_counter
    post.update(comments_count: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  # Attributes: id, user_id, post_id, updated_at, created_at

  # Callbacks
  after_save :update_post_likes_counter

  # Methods
  def update_post_likes_counter
    post.update(likes_count: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  # Attributes: id, author_id, title, text, updated_at, created_at, comments_count, likes_count

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_count, numericality: { greater_than_or_equal_to: 0, only_integer: true, allow_blank: true }
  validates :likes_count, numericality: { greater_than_or_equal_to: 0, only_integer: true, allow_blank: true }

  # callback
  after_save :update_user_posts_counter

  def recent_comments(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end

  def update_user_posts_counter
    author.update(posts_count: author.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  #  attr_accessible :name, :bio, :photo, :email, :password, :password_confirmation, :confirmed_at

  has_many :comments
  has_many :likes
  has_many :posts, foreign_key: 'author_id'

  # Attributes: id, name, email, encrypted_password,
  # reset_password_token,
  # reset_password_sent_at,
  # remember_created_at,
  # created_at,
  # updated_at,
  # bio,
  # photo,
  # confirmed_at

  # Validations
  validates :name, presence: true
  validates :posts_count, numericality: {
    greater_than_or_equal_to: 0,
    only_integer: true,
    allow_blank: true
  }

  # method
  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name bio photo])
  end

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :bio, :photo, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_user_and_post, only: %i[new create]

  def new
    @comment = @post.comments.new
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.author = @user

    if @comment.save
      flash[:notice] = 'Comment created successfully.'
      redirect_to user_post_path(@user, @post)
    else
      render 'new'
    end
  end

  private

  def set_user_and_post
    @user = current_user
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # Placeholder action for the root URL
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @like = @post.likes.build(post: @post, author: @user)
    if @like.save
      # Like successfully created
    end
    redirect_to user_post_path(@user, @post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user_id = params[:user_id]
    @user = User.find_by(id: @user_id)
    @posts = Post.includes(:comments).where(author_id: params[:user_id])
    # @recent_comments = @posts.recent_comments
    # Placeholder action for the 'users/:user_id/posts' URL
  end

  def show
    @user_id = params[:user_id]
    @post_id = params[:id]
    @post = Post.includes(comments: :author).find_by(id: @post_id)
    # Placeholder action for the 'users/:user_id/posts/:id' URL
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      # Post successfully created
      flash[:notice] = 'Post created successfully.'
      redirect_to user_path(current_user)

    else
      # Handle validation errors
      render :new
    end
  end

  def new
    @user = current_user
    @post = @user.posts.new
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all # Assuming you have a User model
    # Additional logic if needed
  end

  def show
    @user_id = params[:id]
    @user = User.find_by(id: @user_id)
    @recent_posts = @user.recent_posts
    # Placeholder action for the 'users/:id' URL
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<%= form_with model: @comment,url: user_post_comments_path(@user, @post), local: true do |form| %>
  <div class="container">
  <div class="field"> 
  <%= form.label :text %>
  <%= form.text_area :text %>
  </div>

  <div>
  <%= form.submit "Create Comment" %>
  </div>

  <div>
<% end %>

app/views/home/index.html.erb
<h1>Welcome to the Homepage</h1>
<p>This is the landing page for your application.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="container">

<div class="all-container">
<div class="img-container">
<img src="<%= @user.photo %>" alt="img" />
</div>
<div class="user-container">
<h4 class="name"><%= @user.name %></h4>
<div class="posts">
<p>Number of posts: <%= @user.posts_count %></p>
</div>
</div>
</div>

<div class="main-container">
<% @posts.each do |post| %>
<a href = "<%= user_post_path(@user, post) %>" class="bio p">
<h3> <%= post.title %></h3>
<p> <%= post.text %></p>
<div class="posts">
<p>comments: <%= post.comments_count %> likes: <%= post.likes_count %></p>
</div>
</a>

<ul class="comments">
<li class="comment-title"><strong>Comments: <%= post.comments_count %> </strong></li>
<% post.recent_comments.includes(:author).each do |comment, index| %>
<li><strong><%= comment.author.name %> </strong> <%= comment.text %> </li>
<% end %>

</ul>

<% end %>

<div class="button-container">
<a href= "<%= new_user_post_path(@user, @post) %>" class="btn"> Create new post</a>
</div>

</div>


<div>

app/views/posts/new.html.erb
 
<%= form_with model: [@user, @post], local: true do |form| %>
  <div class="container">
  <div class="field"> 
  <%= form.label :title %>
  <%= form.text_field :title %>
  </div>

  <div class="field"> 
  <%= form.label :text %>
  <%= form.text_area :text %>
  </div>

  <div>
  <%= form.submit "Create Post" %>
  </div>

  <div>
<% end %>

app/views/posts/show.html.erb
<div class="container">
<div class="main-container">
 
<div class="bio p">
<div class="post-detail">
<h3> <%= @post.title %> by <%= @post.author.name %> </h3>
<p>comments: <%= @post.comments_count %> likes: <%= @post.likes_count %></p>
</div>
<p> <%= @post.text %></p>
</div>

<ul class="comments">
<li class="comment-title"><strong>Comments: <%= @post.comments_count %> </strong></li>
<% @post.recent_comments.includes(:author).each do |comment, index| %>
<li><strong><%= comment.author.name %> </strong> <%= comment.text %> </li>
<% end %>

</ul>

<div class="button-container">
<div class="like">
<%= form_with(model: Like.new, url: user_post_likes_path(@user_id, @post)) do |form| %>
    <%= form.submit "Like" %>
  <% end %>
</div>
<a href= "<%= new_user_post_comment_path(@user_id, @post) %>" class="btn"> Add Comment</a>
</div>

<% if user_signed_in? %>
      <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete } %>
  <% end%>
 </div>
 </div>

app/views/users/index.html.erb
<%= stylesheet_link_tag "users" %>
 
<div class="container">

<% if user_signed_in? %>
  <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete } %>
<% else %>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

<h1>All Users</h1>
<% @users.each do |user| %>
<div class="all-container">
<div class="img-container">
<img src="<%= user.photo %>" alt="img" />
</div>
<a href="<%= user_path(user)%>" class="user-container">
<h4 class="name"><%= user.name %></h4>
<div class="posts">
<p>Number of posts: <%= user.posts_count %></p>
</div>
</a>

</div>
<% end %>
 
</div>

app/views/users/show.html.erb
<div class="container">
<div class="all-container">
<div class="img-container">
<img src="<%= @user.photo %>" alt="img" />
</div>
<div class="user-container">
<h4 class="name"><%= @user.name %></h4>
<div class="posts">
<p>Number of posts: <%= @user.posts_count %></p>
</div>
</div>
</div>
<div class="bio">
<h3>Bio</h3>
<p><%= @user.bio %></p>
</div>
<div class="bio">
<% @recent_posts.each do |post| %>
<a href = "<%= user_post_path(@user, post) %>" >
<h3><%= post.title %></h3><p><%= post.text %></p>
<div class="posts">
<p>comments: <%= post.comments_count %> likes: <%= post.likes_count %></p>
</div>
<% end %>
</div>
<div class="button-container">
<a href="<%= user_posts_path(@user) %>" class="btn">see all posts</a>
</div>
</div>